### ISSUE TITLE
mitm6 doesn't work on VPN tunnel interface. "mitm6 -i tun0 -d <domain name>"

### ISSUE THREAD

**Issue by ssc1982** [fox-it/mitm6#16]
root@kali:/opt/mitm6# mitm6 -i tun0 
Traceback (most recent call last):
  File "/usr/local/bin/mitm6", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mitm6/mitm6.py", line 340, in main
    config = Config(args)
  File "/usr/local/lib/python3.8/dist-packages/mitm6/mitm6.py", line 57, in __init__
    self.macaddr = netifaces.ifaddresses(self.default_if)[netifaces.AF_LINK][0]['addr']
KeyError: 17

**Comment by korang** [comment]
SAme issue with CSCOTUN0 cisco anyconnect vpn connection.

**Comment by InitRoot** [comment]
This is due to VPN on layer2 usually doesn't receive MAC addresses.
You can try modifying the code as below for line 57:
```

  if args.mac is None:
            self.macaddr = '00:00:00:00:00:00'
        else:
            self.macaddr = args.mac
```

**Comment by 0x7274** [comment]
> This is due to VPN on layer2 usually doesn't receive MAC addresses. You can try modifying the code as below for line 57:
> 
> ```
> 
>   if args.mac is None:
>             self.macaddr = '00:00:00:00:00:00'
>         else:
>             self.macaddr = args.mac
> ```

thanks mate, works perfectly

**Comment by KreativeNerd** [comment]
![image](https://github.com/user-attachments/assets/6d2d4a3c-eb21-408a-b17e-b8a73a44d4b3)
After following what was written here, the error still persist for me. This is the full error text:
┌──(kali㉿Smart-Hacker)-[~]
└─$ sudo mitm6 -i tun0 -d secdojo.local 
[sudo] password for kali: 
/usr/local/lib/python3.11/dist-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  cipher=algorithms.Blowfish,
/usr/local/lib/python3.11/dist-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated and will be removed in a future release
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "/usr/local/bin/mitm6", line 33, in <module>
    sys.exit(load_entry_point('mitm6==0.3.0', 'console_scripts', 'mitm6')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 369, in main
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 57, in __init__
KeyError: 17

**Comment by dovelus** [comment]
Try to run the python directly instead for example for me was `sudo python3 /opt/mitm6/mitm6/mitm6.py -d <domian> -i tun0`
