### ISSUE TITLE
mitm6 is quiet...TOO quiet?

### ISSUE THREAD

**Issue by braimee** [fox-it/mitm6#17]
Hello!

I've got a brand spanking new Kali VM, fully updated with just a handful of tools on it - one of which (of course!) is mitm6.  I ran it for the first time this week at a customer network, and here's what things look like when it fires up:

````
/opt/mitm6/mitm6/mitm6.py:283: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if arpp.op is 2:
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(mitm6.py:1237): Gdk-CRITICAL **: 08:38:54.206: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Starting mitm6 using the following configuration:
Primary adapter: eth0 [x:x:x:x:x:x]
IPv4 address: x.x.x.x
IPv6 address: x::x:x:x:x
DNS local search domain: network.local
DNS whitelist: network.local
````

The screen just sat there for about 30 minutes and I was anxious to see results start rolling in, but all that eventually coughed up was:

````
Unhandled Error
Traceback (most recent call last):
  File "/opt/mitm6/mitm6/mitm6.py", line 380, in <module>
    main()
  File "/opt/mitm6/mitm6/mitm6.py", line 377, in main
    reactor.run()
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1276, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 875, in runUntilCurrent
    f(*a, **kw)
  File "/opt/mitm6/mitm6/mitm6.py", line 288, in parsepacket
    send_dns_reply(p)
  File "/opt/mitm6/mitm6/mitm6.py", line 179, in send_dns_reply
    if dns.qd.qclass != 1 or dns.qr != 0:
builtins.AttributeError: 'NoneType' object has no attribute 'qclass'

Unhandled Error
Traceback (most recent call last):
  File "/opt/mitm6/mitm6/mitm6.py", line 380, in <module>
    main()
  File "/opt/mitm6/mitm6/mitm6.py", line 377, in main
    reactor.run()
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1276, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 875, in runUntilCurrent
    f(*a, **kw)
  File "/opt/mitm6/mitm6/mitm6.py", line 288, in parsepacket
    send_dns_reply(p)
  File "/opt/mitm6/mitm6/mitm6.py", line 179, in send_dns_reply
    if dns.qd.qclass != 1 or dns.qr != 0:
builtins.AttributeError: 'NoneType' object has no attribute 'qclass'
````

I let the session run a while longer but it was just radio silence after this.  

Any thoughts on what might be the issue?

Thanks,
Brian

**Comment by dirkjanm** [comment]
Hi Brian, it's hard to say what's causing this without knowing the network. Your best bet is to run wireshark while running mitm6 and see if any DHCPv6 traffic is coming by. It should respond to that. If there is no traffic, then mitm6 won't do much either. The errors are mainly from packets that it didn't understand and shouldn't be impacting the normal flow.

**Comment by braimee** [comment]
Thanks @dirkjanm I'll mark this as closed for now as I completed the pentest and found some goodies using other methods.  Could've just been a one-off weird issue or a problem with the user (me) :-).  Have a great day.
