### ISSUE TITLE
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)

### ISSUE THREAD

**Issue by wqreytuk** [fox-it/mitm6#26]
env:
    os:
        win10 education
        Version 20H2 (OS build 19042.1586)
    python:
        Python 3.9.1

mitm6:
    lastest

here is my command to execute mitm6:
`C:\Users\x\AppData\Local\Programs\Python\Python39\python3.exe C:/Users/x/Downloads/dev/mitm6-master/mitm6/mitm6.py --domain mother.fucker --host-allowlist q3eftg2wyhw4yhwyh.mother.fucker --relay ca.mother.fucker -v`

here is the error info:

> C:\Users\x\AppData\Local\Programs\Python\Python39\python3.exe C:/Users/x/Downloads/dev/mitm6-master/mitm6/mitm6.py --domain mother.fucker --host-allowlist q3eftg2wyhw4yhwyh.mother.fucker --relay ca.mother.fucker -v
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\encodings\idna.py", line 167, in encode
    raise UnicodeError("label too long")
> UnicodeError: label too long

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "C:\Users\x\Downloads\dev\mitm6-master\mitm6\mitm6.py", line 412, in <module>
    main()
  File "C:\Users\x\Downloads\dev\mitm6-master\mitm6\mitm6.py", line 404, in main
    dnssock, dnssock2 = setupFakeDns()
  File "C:\Users\x\Downloads\dev\mitm6-master\mitm6\mitm6.py", line 316, in setupFakeDns
    addrinfo = socket.getaddrinfo(fulladdr, 53, socket.AF_INET6, socket.SOCK_DGRAM)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
Starting mitm6 using the following configuration:
Primary adapter: {A8A69050-47C3-4625-A4EE-EF1EF847904F} [00:0c:29:57:de:2a]
IPv4 address: 192.168.25.129
IPv6 address: fe80::954b:7bd0:b382:9e0d
DNS local search domain: mother.fucker
DNS allowlist: mother.fucker
Hostname allowlist: q3eftg2wyhw4yhwyh.mother.fucker
An error occurred while sending a packet: b'{A8A69050-47C3-4625-A4EE-EF1EF847904F}: No such device exists (No such device exists)'
Note that root privileges are required to run mitm6

here is the image version of error info:
![image](https://user-images.githubusercontent.com/48377190/158001612-62f48089-7263-4e58-95c3-776d5853f63a.png)

here is the full stack:
![image](https://user-images.githubusercontent.com/48377190/158001449-54cb872b-69b6-4e8e-b898-70bbb5a88918.png)
![image](https://user-images.githubusercontent.com/48377190/158001474-971c6605-7caf-4d9f-a013-3e74bdd2592c.png)

**Comment by wqreytuk** [comment]
seems like it is not designed for windows:https://github.com/dirkjanm/mitm6/issues/3
