### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [fox-it/mitm6#27]
Hello,

when I run mitm6 don't work, I have this error:

```
Traceback (most recent call last):
  File "/usr/bin/mitm6", line 33, in <module>
    sys.exit(load_entry_point('mitm6==0.3.0', 'console_scripts', 'mitm6')())
  File "/usr/bin/mitm6", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: mitm6
```
I have installed the requirements, my version of Python 3.9.12 and Linux  5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1k

A greeting anf thanks

**Comment by dirkjanm** [comment]
Please try to run this in a virtualenv, this is not an issue with mitm6 but probably some issue with your local installation that I can't help with debugging.
