### ISSUE TITLE
Windows "getaddrinfo failed"

### ISSUE THREAD

**Issue by xXLabRatXx** [fox-it/mitm6#3]
I installed mitm6 with `pip install -r requirements.txt`, and then `setup.py install`. Both commands worked flawlessly without error. The first time I ran mitm6, it error-ed out saying I had to install WinPCAP. I installed it, but now when i run `mitm6 -v` it says: 

```
Starting mitm6 using the following configuration:
Primary adapter: {E3A50949-44E1-4C87-BA7E-EB8103FB0ED2} [80:00:0b:77:c2:bb]
IPv4 address: 172.27.71.64
IPv6 address: fe80::194:f706:e99b:648a
Warning: Not filtering on any domain, mitm6 will reply to all DNS queries.
Unless this is what you want, specify a domain with -d
Traceback (most recent call last):
  File "C:\Python27\Scripts\mitm6-script.py", line 11, in <module>
    load_entry_point('mitm6==0.1.1', 'console_scripts', 'mitm6')()
  File "C:\Python27\lib\site-packages\mitm6\mitm6.py", line 279, in main
    dnssock = setupFakeDns()
  File "C:\Python27\lib\site-packages\mitm6\mitm6.py", line 219, in setupFakeDns

    addrinfo = socket.getaddrinfo(fulladdr, 53, socket.AF_INET6, socket.SOCK_DGRAM)
socket.gaierror: [Errno 11004] getaddrinfo failed
```

How do I fix this?

**Comment by dirkjanm** [comment]
I'm actually surprised it got that far since mitm6 is designed to run on Linux. I will see if it is possible to run it on Windows and how much changes are required.

**Comment by dirkjanm** [comment]
I've got some things running on Windows but for some reason Scapy doesn't seem to get any DHCPv6 messages (though DNS spoofing works after commenting out some unix specific parts). I don't have too much time to dig into this currently, so Windows will have to be unsupported until then.

**Comment by sm00v** [comment]
@dirkjanm any plans to complete the Windows compatibility goal? :)

**Comment by dirkjanm** [comment]
no, but you can use https://github.com/Kevin-Robertson/InveighZero which supports DHCPv6 spoofing
