### ISSUE TITLE
builtins.IndexError: list index out of range`

### ISSUE THREAD

**Issue by digitalohm** [fox-it/mitm6#36]
Not sure what might be happening here or if it's causing a problem

```Unhandled Error
Traceback (most recent call last):
  File "/usr/local/bin/mitm6", line 33, in <module>
    sys.exit(load_entry_point('mitm6==0.3.0', 'console_scripts', 'mitm6')())
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 409, in main

  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1315, in run
    self.mainLoop()
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1325, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 964, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 296, in parsepacket

builtins.IndexError: list index out of range```

**Comment by JaredStemper** [comment]
Getting the same issue on clean install in venv.

There is a chance it is related to issue #13 / #5 that had a similar output when scapy versions changed. The currently version on a fresh kali install from `pip list | grep scapy` is 2.5.0.

Using the recommended workarounds of `pip uninstall scapy` and `pip install scapy==2.4.0` has not remediated the issue, as I receive the same `builtins.IndexError: list index out of range` error.
