### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by mother2110** [fox-it/mitm6#38]
New Kali 2023.3

Not sure about this error..
'
python3 mitm6/mitm6.py          

Traceback (most recent call last):
  File "/opt/mitm6/mitm6/mitm6.py", line 412, in <module>
    main()
  File "/opt/mitm6/mitm6/mitm6.py", line 369, in main
    config = Config(args)
             ^^^^^^^^^^^^
  File "/opt/mitm6/mitm6/mitm6.py", line 57, in __init__
    self.macaddr = netifaces.ifaddresses(self.default_if)[netifaces.AF_LINK][0]['addr']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 17

**Comment by mother2110** [comment]
Im an idiot
