### ISSUE TITLE
Same issue here - Can you use MITM6 using a VPN - tun0 ?

### ISSUE THREAD

**Issue by goodallcsimon** [fox-it/mitm6#42]
mitm6 will launch correctly when using the default or -i eth0

But when I change to -i tun0 - Its fails with a load_entry_point error.

Please help!!

**Comment by dabeersboys** [comment]
I am also having this issue.
Traceback (most recent call last):
  File "/usr/local/bin/mitm6", line 33, in <module>
    sys.exit(load_entry_point('mitm6==0.3.0', 'console_scripts', 'mitm6')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 369, in main
  File "/usr/local/lib/python3.11/dist-packages/mitm6-0.3.0-py3.11.egg/mitm6/mitm6.py", line 57, in __init__
KeyError: 17

**Comment by hazartaspinar** [comment]
i have a exaclty same problem pls help us

**Comment by as33r** [comment]
https://github.com/dirkjanm/mitm6/issues/16 sometime tun0 does not have mac address, you can make changes at line 57, add a pseudo MAC address. 

```
if args.mac is None:
    self.macaddr = '00:00:00:00:00:00'
else:
    self.macaddr = args.mac
```
