### ISSUE TITLE
ImportError: cannot import name 'reactor'

### ISSUE THREAD

**Issue by blshkv** [fox-it/mitm6#9]
I have an installed twisted v 17.1.0 however i'm geting the following error:
```
mitm6 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/mitm6", line 11, in <module>
    load_entry_point('mitm6==0.2.2', 'console_scripts', 'mitm6')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/mitm6/mitm6.py", line 3, in <module>
    from twisted.internet import reactor
ImportError: cannot import name 'reactor'

```

can you specify what is the minimum version of twisted is required?

**Comment by blshkv** [comment]
ok, scratch it. I have tried few other versions without any issues. It must be something wrong with this particular version.
